import { Type } from '@sinclair/typebox'
import type { AgentTool } from '@mariozechner/pi-agent-core'
import type { Env } from '../config.js'
import { insertInvestigation, insertCampaign, getInvestigation, updateInvestigationReport } from '../clients/db.js'

export function createCreateInvestigationTool(env: Env): AgentTool<typeof CreateInvestigationParams> {
  return {
    name: 'create_investigation',
    label: 'Create Investigation',
    description:
      'Create a threat investigation record with findings, IOCs, and MITRE technique mappings.',
    parameters: CreateInvestigationParams,
    execute: async (_toolCallId, params) => {
      const id = await insertInvestigation(env.DB, params)
      return {
        content: [{ type: 'text' as const, text: `Investigation created: "${params.title}" (ID: ${id}, severity: ${params.severity})` }],
        details: { investigation_id: id },
      }
    },
  }
}

export function createFlagCampaignTool(env: Env): AgentTool<typeof FlagCampaignParams> {
  return {
    name: 'flag_campaign',
    label: 'Flag Campaign',
    description:
      'Flag a coordinated attack campaign linking events across multiple honeypots. Can trigger the responder agent.',
    parameters: FlagCampaignParams,
    execute: async (_toolCallId, params) => {
      const id = await insertCampaign(env.DB, params)
      return {
        content: [{ type: 'text' as const, text: `Campaign flagged: "${params.name}" (ID: ${id}, confidence: ${params.confidence}, ${params.attacker_ips.length} IPs, ${params.affected_honeypots.length} honeypots)` }],
        details: { campaign_id: id },
      }
    },
  }
}

export function createGenerateReportTool(env: Env): AgentTool<typeof GenerateReportParams> {
  return {
    name: 'generate_report',
    label: 'Generate Report',
    description:
      'Generate a markdown threat report for an investigation. Includes executive summary, findings, IOCs, and MITRE mapping.',
    parameters: GenerateReportParams,
    execute: async (_toolCallId, params) => {
      const data = await getInvestigation(env.DB, params.investigation_id)
      if (!data) throw new Error(`Investigation ${params.investigation_id} not found`)

      const findings = JSON.parse(data.findings as string ?? '[]') as Array<{ type: string; description: string; evidence?: string }>
      const iocs = JSON.parse(data.iocs as string ?? '[]') as Array<{ type: string; value: string; context?: string }>
      const techniques = JSON.parse(data.mitre_techniques as string ?? '[]') as string[]
      const eventIds = JSON.parse(data.event_ids as string ?? '[]') as string[]

      const report = `# Threat Investigation Report

## ${data.title}

**Severity:** ${data.severity}
**Status:** ${data.status}
**Created:** ${data.created_at}

## Executive Summary

${data.summary}

## Findings

${findings.map((f, i) => `### ${i + 1}. ${f.type}\n${f.description}${f.evidence ? `\n\n**Evidence:** ${f.evidence}` : ''}`).join('\n\n')}

## Indicators of Compromise

| Type | Value | Context |
|------|-------|---------|
${iocs.map((ioc) => `| ${ioc.type} | \`${ioc.value}\` | ${ioc.context ?? '-'} |`).join('\n')}

## MITRE ATT&CK Techniques

${techniques.map((t) => `- ${t}`).join('\n')}

## Related Events

${eventIds.length} events linked to this investigation.

---
*Generated by agentic-hop Investigator Agent*`

      await updateInvestigationReport(env.DB, params.investigation_id, report)

      return {
        content: [{ type: 'text' as const, text: report }],
        details: { investigation_id: params.investigation_id },
      }
    },
  }
}

// --- Schemas ---

const CreateInvestigationParams = Type.Object({
  tenant_id: Type.String({ description: 'Tenant UUID' }),
  title: Type.String({ description: 'Investigation title' }),
  summary: Type.String({ description: 'Detailed summary of findings' }),
  severity: Type.String({ description: 'Severity: low, medium, high, critical' }),
  findings: Type.Array(Type.Object({
    type: Type.String({ description: 'Finding type' }),
    description: Type.String({ description: 'Finding description' }),
    evidence: Type.Optional(Type.String({ description: 'Supporting evidence' })),
  })),
  iocs: Type.Array(Type.Object({
    type: Type.String({ description: 'IOC type: ip, domain, hash, url, email' }),
    value: Type.String({ description: 'IOC value' }),
    context: Type.Optional(Type.String({ description: 'Context' })),
  })),
  mitre_techniques: Type.Array(Type.String(), { description: 'MITRE ATT&CK technique IDs' }),
  event_ids: Type.Array(Type.String(), { description: 'Event UUIDs linked to this investigation' }),
})

const FlagCampaignParams = Type.Object({
  tenant_id: Type.String({ description: 'Tenant UUID' }),
  investigation_id: Type.Optional(Type.String({ description: 'Parent investigation UUID' })),
  name: Type.String({ description: 'Campaign name' }),
  description: Type.String({ description: 'Campaign description' }),
  attacker_ips: Type.Array(Type.String(), { description: 'Source IPs' }),
  affected_honeypots: Type.Array(Type.String(), { description: 'Deployment UUIDs targeted' }),
  event_ids: Type.Array(Type.String(), { description: 'Event UUIDs' }),
  mitre_chain: Type.Array(Type.String(), { description: 'Ordered MITRE technique chain' }),
  confidence: Type.Number({ description: 'Attribution confidence 0.0-1.0', minimum: 0, maximum: 1 }),
})

const GenerateReportParams = Type.Object({
  investigation_id: Type.String({ description: 'Investigation UUID to generate report for' }),
})
